import type { NextPage } from 'next'
import React, { useState } from 'react'
import Head from 'next/head'
import Footer from './footer'
import Forms from  './forms'
import Success_registr from './success_registr'
import main_img from '../static/main_screen.svg';
import Image from 'next/image';
import 'antd/dist/antd.css';

const Home: NextPage = () => {

  const [formData, setFormData]=useState<Validation | undefined>();

  return (
    <div className="Home">
      <Head>
        <title>NextJs Sign Up Text Task</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="Home__main-container">
        <Image 
          src={main_img} 
          alt="mainScrImg" 
          className="MainImg"
        />

        {formData !== undefined ? (
          <Success_registr firstname={formData.firstname} setFormData={setFormData}/>
        ) : (
          <Forms formData={formData} setFormData={setFormData}/>
        )}

      </div>
      
      <Footer />
    </div>
  )
}

export default Home
